global dcv_root
dcv_root = '/home/daley/research/dcv';

addpath([...
    dcv_root, '/matlab:', ...
    dcv_root, '/contrib/siftDemoV4:', ...
    dcv_root, '/contrib/vgg_examples:', ...
    dcv_root, '/contrib/vgg_multiview:', ...
    dcv_root, '/contrib/vgg_numerics:', ...
    dcv_root, '/contrib/vgg_general:', ...
    dcv_root, '/contrib/vgg_ui:', ...
    dcv_root, '/contrib/MatlabFns/Match:', ...
    dcv_root, '/contrib/MatlabFns/Robust:', ...
    dcv_root, '/contrib/MatlabFns/Misc:', ...
    dcv_root, '/contrib/MatlabFns/Projective:', ...
    dcv_root, '/contrib/MatlabFns/Spatial:', ...
    ...
]);
run([dcv_root, '/contrib/vlfeat/toolbox/vl_setup']);
