dcv_root = '/home/daley/research/dcv';

p = [...
    dcv_root, '/matlab:', ...
    dcv_root, '/dropins/siftDemoV4:', ...
    dcv_root, '/dropins/vgg_examples:', ...
    dcv_root, '/dropins/vgg_multiview:', ...
    dcv_root, '/dropins/vgg_numerics:', ...
    dcv_root, '/dropins/vgg_general:', ...
    dcv_root, '/dropins/vgg_ui:', ...
    dcv_root, '/dropins/MatlabFns/Match:', ...
    dcv_root, '/dropins/MatlabFns/Robust:', ...
    dcv_root, '/dropins/MatlabFns/Misc:', ...
    dcv_root, '/dropins/MatlabFns/Projective:', ...
    dcv_root, '/dropins/MatlabFns/Spatial:', ...
    ...
];

addpath(p);
run([dcv_root, '/dropins/vlfeat/toolbox/vl_setup']);
